# object detector boot.py
# generated by maixhub.com

import sensor, image, lcd, time
import KPU as kpu
import gc, sys

def RecordDataset(DatasetName, LCD_Rotation = 0, SensorHmirror = False, SensorVflip = False , SensorWindow=(224, 224)):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(SensorWindow)
    sensor.set_hmirror(SensorHmirror)
    sensor.set_vflip(SensorVflip)
    sensor.run(1)

    lcd.init(type=1)
    lcd.rotation(LCD_Rotation)
    lcd.clear(lcd.WHITE)

    lastShotTime = 0
    numberOfPhotos = 0
    while True:
        img = sensor.snapshot()
        if(time.ticks_ms() - lastShotTime > 50):
            img.save("/sd/" + DatasetName + "/" + DatasetName + "_" + str(time.ticks_ms()) + ".jpg", quality = 99)
            numberOfPhotos += 1
            img.draw_string(0, 0, "Saveing photo " + str(numberOfPhotos) + " ..")
        else:
            img.draw_string(0, 0, str(time.ticks_ms()))
        lcd.display(img)


if __name__ == "__main__":
    RecordDataset(DatasetName = "Orange3", LCD_Rotation = 2, SensorHmirror = True, SensorVflip = True)
