# object detector boot.py
# generated by maixhub.com

import sensor, image, lcd, time
import KPU as kpu


def main():
    anchors = [3.8125, 3.8125, 5.375, 5.375, 7.1875, 7.1875, 11.25, 11.3125, 9.125, 9.125]
    model_addr = "/sd/m.kmodel"

    startTime = time.ticks_ms()
    for i in range(100):
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.3, 0.3, 5, anchors)
        print(time.ticks_ms() - startTime)
        startTime = time.ticks_ms()
        kpu.deinit(task)


if __name__ == "__main__":
    main()