/*
 * TimerInterrupts.h
 *
 *  Created on: 2021Äê6ÔÂ17ÈÕ
 *      Author: h13
 */

#ifndef PLATFORM_INTERRUPTS_TIMERINTERRUPTS_TIMERINTERRUPTS_H_
#define PLATFORM_INTERRUPTS_TIMERINTERRUPTS_TIMERINTERRUPTS_H_



#endif /* PLATFORM_INTERRUPTS_TIMERINTERRUPTS_TIMERINTERRUPTS_H_ */
